name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  # Lint Lua Modules
  # --------------------------------------------------
  lint_modules:
    name: Lua Modules (linter)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            dagger.json
            .dagger
            lua
      - name: Call Dagger
        uses: dagger/dagger-for-github@v6
        with:
          args: lint-modules --src=.:modules
          cloud-token: p.eyJ1IjogIjFiZjEwMmRjLWYyZmQtNDVhNi1iNzM1LTgxNzI1NGFkZDU2ZiIsICJpZCI6ICI4ZmZmNmZkMi05MDhiLTQ4YTEtOGQ2Zi1iZWEyNGRkNzk4MTkifQ.l1Sf1gB37veXUWhxOgmjvjYcrh32NiuovbMxvjVI7Z0

  # Core Unit Tests
  # --------------------------------------------------
  test_core:
    name: Core Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            dagger.json
            .dagger
            core
            deps/libz
          lfs: "true"
      - name: Call Dagger
        uses: dagger/dagger-for-github@v6
        with:
          args: test-core --src=.:test-core
          cloud-token: p.eyJ1IjogIjFiZjEwMmRjLWYyZmQtNDVhNi1iNzM1LTgxNzI1NGFkZDU2ZiIsICJpZCI6ICI4ZmZmNmZkMi05MDhiLTQ4YTEtOGQ2Zi1iZWEyNGRkNzk4MTkifQ.l1Sf1gB37veXUWhxOgmjvjYcrh32NiuovbMxvjVI7Z0

  # Format
  # --------------------------------------------------
  lint_core:
    name: Core clang-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: "true"
      - name: Call Dagger
        uses: dagger/dagger-for-github@v6
        with:
          args: lint-core --src=.:lint-core
          cloud-token: p.eyJ1IjogIjFiZjEwMmRjLWYyZmQtNDVhNi1iNzM1LTgxNzI1NGFkZDU2ZiIsICJpZCI6ICI4ZmZmNmZkMi05MDhiLTQ4YTEtOGQ2Zi1iZWEyNGRkNzk4MTkifQ.l1Sf1gB37veXUWhxOgmjvjYcrh32NiuovbMxvjVI7Z0
